# Generated by Django 5.0.7 on 2024-07-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите полное имя контакта', max_length=122, verbose_name='Полное имя')),
                ('email', models.EmailField(help_text='Введите адрес эелектронной почты контакта', max_length=122, verbose_name='Адрес электронной почты')),
                ('phone', models.CharField(help_text='Введите номер телефона', max_length=122, verbose_name='Номер телефона')),
                ('description', models.TextField(help_text='Введиет описание или дополнительную информацию', verbose_name='Описание')),
            ],
        ),
    ]
